// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWuU_CjLZuQRD7eonZe6qrj8pC15l7pE',
    appId: '1:457023541080:web:7f33296f9c9ba24c9e9f2d',
    messagingSenderId: '457023541080',
    projectId: 'uasmediasosial',
    authDomain: 'uasmediasosial.firebaseapp.com',
    storageBucket: 'uasmediasosial.appspot.com',
    measurementId: 'G-X4FHBNYF1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFaBvv7z_ULbtTTOUb7gShnPEATYvizY',
    appId: '1:457023541080:android:d444eac37ec306819e9f2d',
    messagingSenderId: '457023541080',
    projectId: 'uasmediasosial',
    storageBucket: 'uasmediasosial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNcfmKlOHexT9fyyzH9Z46t4gLzoKg-7Q',
    appId: '1:457023541080:ios:f99cd974d97addc89e9f2d',
    messagingSenderId: '457023541080',
    projectId: 'uasmediasosial',
    storageBucket: 'uasmediasosial.appspot.com',
    iosBundleId: 'com.example.uasSosialmedia',
  );
}
